//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KlientWcf.KotkiServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Kotek", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceContract")]
    [System.SerializableAttribute()]
    public partial class Kotek : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string plecField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string plec {
            get {
                return this.plecField;
            }
            set {
                if ((object.ReferenceEquals(this.plecField, value) != true)) {
                    this.plecField = value;
                    this.RaisePropertyChanged("plec");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KotkiServiceRef.IKotkiService", CallbackContract=typeof(KlientWcf.KotkiServiceRef.IKotkiServiceCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IKotkiService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IKotkiService/DodajKotka")]
        void DodajKotka(KlientWcf.KotkiServiceRef.Kotek k);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IKotkiService/DodajKotka")]
        System.Threading.Tasks.Task DodajKotkaAsync(KlientWcf.KotkiServiceRef.Kotek k);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IKotkiService/GetKotki")]
        void GetKotki();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IKotkiService/GetKotki")]
        System.Threading.Tasks.Task GetKotkiAsync();
        
        // CODEGEN: Trwa generowanie kontraktu komunikatu, ponieważ nazwa elementu p z przestrzeni nazw http://tempuri.org/ nie ma atrybutu nillable.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IKotkiService/GetKotkiByGender")]
        void GetKotkiByGender(KlientWcf.KotkiServiceRef.GetKotkiByGender request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IKotkiService/GetKotkiByGender")]
        System.Threading.Tasks.Task GetKotkiByGenderAsync(KlientWcf.KotkiServiceRef.GetKotkiByGender request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IKotkiService/RemoveKotek")]
        void RemoveKotek(int idKotka);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IKotkiService/RemoveKotek")]
        System.Threading.Tasks.Task RemoveKotekAsync(int idKotka);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IKotkiServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IKotkiService/AddKotekResult")]
        void AddKotekResult(KlientWcf.KotkiServiceRef.Kotek[] kotki);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IKotkiService/GetKotkiByPlec")]
        void GetKotkiByPlec(KlientWcf.KotkiServiceRef.Kotek[] kotki);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IKotkiService/GetKotkiResult")]
        void GetKotkiResult(KlientWcf.KotkiServiceRef.Kotek[] kotki);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IKotkiService/DeleteKotekResult")]
        void DeleteKotekResult(KlientWcf.KotkiServiceRef.Kotek usunietyKotek);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetKotkiByGender {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetKotkiByGender", Namespace="http://tempuri.org/", Order=0)]
        public KlientWcf.KotkiServiceRef.GetKotkiByGenderBody Body;
        
        public GetKotkiByGender() {
        }
        
        public GetKotkiByGender(KlientWcf.KotkiServiceRef.GetKotkiByGenderBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetKotkiByGenderBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string p;
        
        public GetKotkiByGenderBody() {
        }
        
        public GetKotkiByGenderBody(string p) {
            this.p = p;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IKotkiServiceChannel : KlientWcf.KotkiServiceRef.IKotkiService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KotkiServiceClient : System.ServiceModel.DuplexClientBase<KlientWcf.KotkiServiceRef.IKotkiService>, KlientWcf.KotkiServiceRef.IKotkiService {
        
        public KotkiServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public KotkiServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public KotkiServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public KotkiServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public KotkiServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void DodajKotka(KlientWcf.KotkiServiceRef.Kotek k) {
            base.Channel.DodajKotka(k);
        }
        
        public System.Threading.Tasks.Task DodajKotkaAsync(KlientWcf.KotkiServiceRef.Kotek k) {
            return base.Channel.DodajKotkaAsync(k);
        }
        
        public void GetKotki() {
            base.Channel.GetKotki();
        }
        
        public System.Threading.Tasks.Task GetKotkiAsync() {
            return base.Channel.GetKotkiAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void KlientWcf.KotkiServiceRef.IKotkiService.GetKotkiByGender(KlientWcf.KotkiServiceRef.GetKotkiByGender request) {
            base.Channel.GetKotkiByGender(request);
        }
        
        public void GetKotkiByGender(string p) {
            KlientWcf.KotkiServiceRef.GetKotkiByGender inValue = new KlientWcf.KotkiServiceRef.GetKotkiByGender();
            inValue.Body = new KlientWcf.KotkiServiceRef.GetKotkiByGenderBody();
            inValue.Body.p = p;
            ((KlientWcf.KotkiServiceRef.IKotkiService)(this)).GetKotkiByGender(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task KlientWcf.KotkiServiceRef.IKotkiService.GetKotkiByGenderAsync(KlientWcf.KotkiServiceRef.GetKotkiByGender request) {
            return base.Channel.GetKotkiByGenderAsync(request);
        }
        
        public System.Threading.Tasks.Task GetKotkiByGenderAsync(string p) {
            KlientWcf.KotkiServiceRef.GetKotkiByGender inValue = new KlientWcf.KotkiServiceRef.GetKotkiByGender();
            inValue.Body = new KlientWcf.KotkiServiceRef.GetKotkiByGenderBody();
            inValue.Body.p = p;
            return ((KlientWcf.KotkiServiceRef.IKotkiService)(this)).GetKotkiByGenderAsync(inValue);
        }
        
        public void RemoveKotek(int idKotka) {
            base.Channel.RemoveKotek(idKotka);
        }
        
        public System.Threading.Tasks.Task RemoveKotekAsync(int idKotka) {
            return base.Channel.RemoveKotekAsync(idKotka);
        }
    }
}
