//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Car", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    public partial class Car : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private string BrandField;
        
        private double HpField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Brand
        {
            get
            {
                return this.BrandField;
            }
            set
            {
                this.BrandField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double Hp
        {
            get
            {
                return this.HpField;
            }
            set
            {
                this.HpField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IRestService")]
public interface IRestService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/getAllXml", ReplyAction="http://tempuri.org/IRestService/getAllXmlResponse")]
    WcfService.Car[] getAllXml();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/getAllXml", ReplyAction="http://tempuri.org/IRestService/getAllXmlResponse")]
    System.Threading.Tasks.Task<WcfService.Car[]> getAllXmlAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/getByIdXml", ReplyAction="http://tempuri.org/IRestService/getByIdXmlResponse")]
    WcfService.Car getByIdXml(string id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/getByIdXml", ReplyAction="http://tempuri.org/IRestService/getByIdXmlResponse")]
    System.Threading.Tasks.Task<WcfService.Car> getByIdXmlAsync(string id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/addXml", ReplyAction="http://tempuri.org/IRestService/addXmlResponse")]
    string addXml(WcfService.Car car);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/addXml", ReplyAction="http://tempuri.org/IRestService/addXmlResponse")]
    System.Threading.Tasks.Task<string> addXmlAsync(WcfService.Car car);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/deleteXml", ReplyAction="http://tempuri.org/IRestService/deleteXmlResponse")]
    WcfService.Car deleteXml(string id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/deleteXml", ReplyAction="http://tempuri.org/IRestService/deleteXmlResponse")]
    System.Threading.Tasks.Task<WcfService.Car> deleteXmlAsync(string id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/getAllJson", ReplyAction="http://tempuri.org/IRestService/getAllJsonResponse")]
    WcfService.Car[] getAllJson();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/getAllJson", ReplyAction="http://tempuri.org/IRestService/getAllJsonResponse")]
    System.Threading.Tasks.Task<WcfService.Car[]> getAllJsonAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/getByIdJson", ReplyAction="http://tempuri.org/IRestService/getByIdJsonResponse")]
    WcfService.Car getByIdJson(string id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/getByIdJson", ReplyAction="http://tempuri.org/IRestService/getByIdJsonResponse")]
    System.Threading.Tasks.Task<WcfService.Car> getByIdJsonAsync(string id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/addJson", ReplyAction="http://tempuri.org/IRestService/addJsonResponse")]
    string addJson(WcfService.Car car);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/addJson", ReplyAction="http://tempuri.org/IRestService/addJsonResponse")]
    System.Threading.Tasks.Task<string> addJsonAsync(WcfService.Car car);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/deleteJson", ReplyAction="http://tempuri.org/IRestService/deleteJsonResponse")]
    WcfService.Car deleteJson(string id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/deleteJson", ReplyAction="http://tempuri.org/IRestService/deleteJsonResponse")]
    System.Threading.Tasks.Task<WcfService.Car> deleteJsonAsync(string id);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IRestServiceChannel : IRestService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class RestServiceClient : System.ServiceModel.ClientBase<IRestService>, IRestService
{
    
    public RestServiceClient()
    {
    }
    
    public RestServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public RestServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RestServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RestServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public WcfService.Car[] getAllXml()
    {
        return base.Channel.getAllXml();
    }
    
    public System.Threading.Tasks.Task<WcfService.Car[]> getAllXmlAsync()
    {
        return base.Channel.getAllXmlAsync();
    }
    
    public WcfService.Car getByIdXml(string id)
    {
        return base.Channel.getByIdXml(id);
    }
    
    public System.Threading.Tasks.Task<WcfService.Car> getByIdXmlAsync(string id)
    {
        return base.Channel.getByIdXmlAsync(id);
    }
    
    public string addXml(WcfService.Car car)
    {
        return base.Channel.addXml(car);
    }
    
    public System.Threading.Tasks.Task<string> addXmlAsync(WcfService.Car car)
    {
        return base.Channel.addXmlAsync(car);
    }
    
    public WcfService.Car deleteXml(string id)
    {
        return base.Channel.deleteXml(id);
    }
    
    public System.Threading.Tasks.Task<WcfService.Car> deleteXmlAsync(string id)
    {
        return base.Channel.deleteXmlAsync(id);
    }
    
    public WcfService.Car[] getAllJson()
    {
        return base.Channel.getAllJson();
    }
    
    public System.Threading.Tasks.Task<WcfService.Car[]> getAllJsonAsync()
    {
        return base.Channel.getAllJsonAsync();
    }
    
    public WcfService.Car getByIdJson(string id)
    {
        return base.Channel.getByIdJson(id);
    }
    
    public System.Threading.Tasks.Task<WcfService.Car> getByIdJsonAsync(string id)
    {
        return base.Channel.getByIdJsonAsync(id);
    }
    
    public string addJson(WcfService.Car car)
    {
        return base.Channel.addJson(car);
    }
    
    public System.Threading.Tasks.Task<string> addJsonAsync(WcfService.Car car)
    {
        return base.Channel.addJsonAsync(car);
    }
    
    public WcfService.Car deleteJson(string id)
    {
        return base.Channel.deleteJson(id);
    }
    
    public System.Threading.Tasks.Task<WcfService.Car> deleteJsonAsync(string id)
    {
        return base.Channel.deleteJsonAsync(id);
    }
}
